name: Run Pytests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Install self
              run: |
                  python setup.py sdist bdist_wheel clean --all develop
                  pip install dist/commnon_tools-0.1.0-py3-none-any.whl --force-reinstall --no-cache-dir
            - name: Test with pytest
              run: |
                  coverage run -m pytest -V -s
            - name: Coverage Report
              run: |
                  coverage report -m
