name: Run Pytests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -e .
            - name: Pip Show
              run: pip show -f common-tools
            - name: Test with pytest
              run: coverage run -m pytest --import-mode=append tests/
            - name: Coverage Report
              run: coverage report -m
