name: Run Pytests

on: [push, pull_request]

env:
    VERSION: "0.1.0"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python setup.py sdist bdist_wheel clean --all develop
                pip install dist/common_tools-$VERSION-py3-none-any.whl --force-reinstall --no-cache-dir
            - name: Pip Freeze
              run: |
                pip freeze
                pip show -f common-tools
            - name: Test with pytest
              run: coverage run -m pytest .
            - name: Coverage Report
              run: coverage report -m
